---
- name: Get the current kernel release.
  command: uname -r
  changed_when: false
  register: kernel_release

- name: Ensure necessary packages are installed.
  yum: "pkg={{ item }} state=installed"
  with_items:
    - wget
    - perl
    - cpp
    - gcc
    - make
    - bzip2
    - kernel-headers
    - kernel-devel
    - "kernel-devel-{{ kernel_release.stdout }}"
    - libselinux-python
    - maven
    - git

- name: Adding epel repository
  shell: rpm -ivh http://mirror.pnl.gov/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

- name: install the latest version of Ansible
  yum:
    name:"{{ item }}"
    state: latest
  with_items:
    - python-setuptools
    - ansible

# Allow Ansible to connect to localhost.
- name: Include Ansible localhost to "/etc/ansible/hosts" file
  lineinfile:
    dest: /etc/ansible/hosts
    regexp: '^localhost ansible_connection=local'
    line: 'localhost ansible_connection=local'
    state: present

# Add Softlayer Setup to VM
- include: softlayer.yml

# Fix slow DNS.
- name: Fix slow DNS (adapted from Bento).
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present

- name: Restart network service (explicitly).
  service: name=network state=restarted

# Cleanup tasks.
- name: Remove unneeded packages.
  yum: "pkg={{ item }} state=absent"
  with_items:
    - cpp
    - kernel-devel
    - kernel-headers

- name: Clean up yum.
  command: yum clean all

- name: Remove RedHat interface persistence (step 1).
  shell: rm -f /etc/udev/rules.d/70-persistent-net.rules

- name: Remove RedHat interface persistence (step 2).
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^HWADDR'
    - '^UUID'
