---
# Install pip
- name: Installing pip
  easy_install:
    name: pip

# Install Softlayer Python Library
- name: Installing Softlayer Python Library
  pip:
    name: softlayer
    state: latest

# Add Cloud Inventory to Ansible
- name: Getting softlayer.py Inventory Artifact
  uri:
    url: "http://gitlab.apicloud.com/qingbo.song/ansible/raw/79f2dca60a80839ab656eef656522fbef002e7af/plugins/inventory/softlayer.py"
    method: GET
    follow_redirects: all
    return_content: yes
    HEADER_Content-Type: "text/plain"
    dest: "/etc/ansible/softlayer.py"

- name: Checking the Ansible Modules Directory
  shell: '[ -d /usr/lib/python*/site-packages/ansible/modules ] && echo /usr/lib/python*/site-packages/ansible/modules'
  args:
    executable: /bin/bash
  register: ansible_modules_path

- name: Checking for Softlayer Ansible Module Artifact
  stat:
    path: "{{ansible_modules_path.stdout}}/core/cloud/softlayer/sl_vm.py"
  register: sl_exists

- debug: msg={{sl_exists}}

- name: Creating Softlayer Modules Directory
  file: 
    path: "{{ansible_modules_path.stdout}}/core/cloud/softlayer"
    state: directory 
    mode: 0755
  when: ansible_modules_path.changed == true

# Add Softlayer Module to Pre-2.x Release of Ansible
- name: Getting Softlayer Ansible Module Artifact
  uri:
    url: "https://raw.githubusercontent.com/ansible/ansible-modules-extras/devel/cloud/softlayer/sl_vm.py"
    method: GET
    follow_redirects: all
    return_content: yes
    HEADER_Content-Type: "text/plain"
    dest: "{{ansible_modules_path.stdout}}/core/cloud/softlayer/sl_vm.py"
  when: ansible_modules_path.changed == true
